-- MySQL Script generated by MySQL Workbench
-- 01/08/17 16:56:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HDSystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HDSystem` ;

-- -----------------------------------------------------
-- Schema HDSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HDSystem` DEFAULT CHARACTER SET utf8 ;
USE `HDSystem` ;

-- -----------------------------------------------------
-- Table `HDSystem`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`category` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`subcategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`subcategory` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`subcategory` (
  `subcategory_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`subcategory_id`),
  INDEX `fk_subcategory_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_subcategory_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `HDSystem`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`hddesignation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`hddesignation` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`hddesignation` (
  `hd_designation_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`hd_designation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`engineer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`engineer` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`engineer` (
  `engineer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `hd_designation_id` INT NOT NULL,
  PRIMARY KEY (`engineer_id`),
  INDEX `fk_engineer_hd_designation1_idx` (`hd_designation_id` ASC),
  CONSTRAINT `fk_engineer_hd_designation1`
    FOREIGN KEY (`hd_designation_id`)
    REFERENCES `HDSystem`.`hddesignation` (`hd_designation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`urgency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`urgency` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`urgency` (
  `urgency_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`urgency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`usercategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`usercategory` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`usercategory` (
  `user_category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`user` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NULL,
  `designation` VARCHAR(45) NULL,
  `parent_p_no` INT NULL,
  `parent_company` VARCHAR(45) NULL,
  `host_p_no` INT NULL,
  `host_company` VARCHAR(45) NULL,
  `user_category_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_user_category1_idx` (`user_category_id` ASC),
  CONSTRAINT `fk_user_user_category1`
    FOREIGN KEY (`user_category_id`)
    REFERENCES `HDSystem`.`usercategory` (`user_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`issue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`issue` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`issue` (
  `issue_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `engineer_id` INT NOT NULL,
  `subcategory_id` INT NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `urgency_id` INT NOT NULL,
  `attachment` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`issue_id`, `engineer_id`, `user_id`),
  INDEX `fk_issue_subcategory1_idx` (`subcategory_id` ASC),
  INDEX `fk_issue_engineer2_idx` (`engineer_id` ASC),
  INDEX `fk_issue_urgency1_idx` (`urgency_id` ASC),
  INDEX `fk_issue_user2_idx` (`user_id` ASC),
  CONSTRAINT `fk_issue_subcategory1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `HDSystem`.`subcategory` (`subcategory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issue_engineer2`
    FOREIGN KEY (`engineer_id`)
    REFERENCES `HDSystem`.`engineer` (`engineer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issue_urgency1`
    FOREIGN KEY (`urgency_id`)
    REFERENCES `HDSystem`.`urgency` (`urgency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issue_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `HDSystem`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`status` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HDSystem`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HDSystem`.`activity` ;

CREATE TABLE IF NOT EXISTS `HDSystem`.`activity` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `current_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `description` VARCHAR(45) NULL,
  `status_id` INT NOT NULL,
  `attachment` VARCHAR(45) NULL,
  `issue_id` INT NOT NULL,
  `issue_engineer_id` INT NOT NULL,
  `issue_user_id` INT NOT NULL,
  PRIMARY KEY (`activity_id`),
  INDEX `fk_activity_status1_idx` (`status_id` ASC),
  INDEX `fk_activity_issue1_idx` (`issue_id` ASC, `issue_engineer_id` ASC, `issue_user_id` ASC),
  CONSTRAINT `fk_activity_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `HDSystem`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_issue1`
    FOREIGN KEY (`issue_id` , `issue_engineer_id` , `issue_user_id`)
    REFERENCES `HDSystem`.`issue` (`issue_id` , `engineer_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `HDSystem`.`hddesignation`
-- -----------------------------------------------------
START TRANSACTION;
USE `HDSystem`;
INSERT INTO `HDSystem`.`hddesignation` (`hd_designation_id`, `name`) VALUES (1, 'Manager');
INSERT INTO `HDSystem`.`hddesignation` (`hd_designation_id`, `name`) VALUES (2, 'Coordinator');
INSERT INTO `HDSystem`.`hddesignation` (`hd_designation_id`, `name`) VALUES (3, 'Engineer');

COMMIT;

